### ISSUE TITLE
Auto tests on Linux and Windows now fail

### ISSUE THREAD

**Issue by zhangcs** [FaspDevTeam/OpenCAEPoro#15]
### Describe the bug

Auto tests on Linux and Windows now fail

### Reproduction

See github->actions

### Expected behavior

N/A

### System Info

```shell
N/A
```

### Validations

- [X] Read the [docs](https://faspdevteam.github.io/OpenCAEPoro).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by billcxx** [comment]
I will check the reason today

**Comment by billcxx** [comment]
fixed with 94fcc3a4599ac2acba788b7cb76bf9c8458cc7ac
Since file glob is not recommended bt cmake, we need to add new files to the cmake file when new files are added,

**Comment by billcxx** [comment]
Previous comment is for build not test.
5df489ea1049c3a6827afcfed78be6d39d3de312 fix the linux test

**Comment by billcxx** [comment]
4328b751fe7794b48fd8f6ca7dff08fdf335c58b and cc2d098deab4b73fe213641afc32f2422bb77023 fix the windows test
